# Generated by Django 5.2.6 on 2025-09-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_category",
                    models.CharField(max_length=150, verbose_name="Категория"),
                ),
                ("description_category", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name_category"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Наименование"
                    ),
                ),
                ("description_product", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(upload_to="product", verbose_name="Фотография"),
                ),
                (
                    "price_all",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите стоимость покупки",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name_product"],
            },
        ),
    ]
